name: Auto PR from dev to master

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create PR from dev to master
        uses: peter-evans/pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: dev
          target: master
          title: "Automated PR: dev → master"
          body: "This pull request was automatically created on push to dev."
          draft: false
